# Generated by Django 3.2.1 on 2021-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0002_systems_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systems',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Иконка fontawesome'),
        ),
        migrations.AlterField(
            model_name='systems',
            name='is_visible',
            field=models.BooleanField(verbose_name='Видимость в меню'),
        ),
    ]
