# Generated by Django 3.2.1 on 2021-05-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0003_auto_20210511_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systems',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка fontawesome'),
        ),
    ]
