# Generated by Django 3.2.1 on 2021-05-11 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0005_params'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='params',
            unique_together={('name', 'system')},
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butlercfg.params', verbose_name='Параметр')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butlercfg.rooms', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['room'],
                'unique_together': {('room', 'param')},
            },
        ),
    ]
