# Generated by Django 3.2.1 on 2021-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0006_auto_20210511_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Вендор',
                'verbose_name_plural': 'Вендоры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['name'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='params',
            options={'ordering': ['system'], 'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
    ]
