# Generated by Django 3.2.1 on 2021-05-17 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0009_devices_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Видимость в меню'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='param',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='butlercfg.params', verbose_name='Связаный параметр'),
        ),
    ]
