# Generated by Django 3.2.1 on 2021-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butlercfg', '0011_auto_20210519_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
