# Generated by Django 3.2.1 on 2021-06-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butlersurv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersurv',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='butlersurv.questionsurv', verbose_name='Связаный вопрос'),
        ),
    ]
