# Generated by Django 3.2.1 on 2021-06-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('butlersurv', '0002_alter_answersurv_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParamSurv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=600, verbose_name='Наименование')),
                ('is_use', models.BooleanField(verbose_name='Использовать в опросах')),
                ('partition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='butlersurv.partitionsurv', verbose_name='Связаный раздел')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметр',
            },
        ),
        migrations.RemoveField(
            model_name='answersurv',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionSurv',
        ),
        migrations.AddField(
            model_name='answersurv',
            name='param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='butlersurv.paramsurv', verbose_name='Связаный вопрос'),
        ),
    ]
