# Generated by Django 3.2.1 on 2021-06-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butlersurv', '0003_auto_20210625_0916'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParamSurv',
            new_name='QuestionSurv',
        ),
    ]
