# Generated by Django 3.2.1 on 2021-06-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butlersurv', '0004_rename_paramsurv_questionsurv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersurv',
            old_name='param',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionsurv',
            old_name='param',
            new_name='question',
        ),
    ]
